### ISSUE TITLE
[Feature Request] Use scroll wheel for volume change

### ISSUE THREAD

**Issue by grantralls** [MahdiGhiasi/Xpotify#31] opened 2019-07-08 18:00 UTC
# Feature Request
When in the official Spotify client when the user mouses over the volume bar and uses the scroll wheel on the mouse it changes the volume. I think this is a great feature and I wanted to hear others thoughts on it if it should be implemented.

![volume](https://user-images.githubusercontent.com/9772334/60831771-5d08e900-a188-11e9-981b-c04c24e30e2c.PNG)

**Comment by MahdiGhiasi** [comment] 2019-07-08 18:05
(Duplicate of #26) This is already done and will be available on the next app update.

**Closed as completed by MahdiGhiasi** 2019-07-08 18:05 UTC
Labels: duplicate, enhancement
