### ISSUE TITLE
XpoMusic keeps skipping

### ISSUE THREAD

**Issue by EvilOlaf** [MahdiGhiasi/Xpotify#67] opened 2019-11-02 10:35 UTC
Hey there,

I just installed XpoMusic from the Microsoft Store and authorized it with my Spotify Premium.
Well unfortunately I was not able to play music with it yet as it rapidly skips from track to track without playing anything. The standard Spotify desktop client just works fine (not installed from Microsoft Store though if that makes any difference at all).

Using Windows 10 1803

If there are any further (debug) information I could provide please let me know.

Thanks for reading.

**Comment by LuminarySage** [comment] 2019-11-14 04:13
Potential duplicate with #53

**Comment by EvilOlaf** [comment] 2019-11-15 16:10
Maybe. For me I cannot play songs at all since it keeps skipping.
Retestet on a completely different system with freshly installed Windows 10 1909, same issue.

**Comment by GroxicTinch** [comment] 2019-11-25 08:04
I get this issue as well, it has happened every single time I use XpoMusic, the one workaround I have found is opening the spotify web player and making that play the music, and just control everything from XpoMusic. its dirty but its the only way I can find to get around it.

**Comment by MahdiGhiasi** [comment] 2020-05-20 15:28
Duplicate of #53.

**Closed as completed by MahdiGhiasi** 2020-05-20 15:28 UTC
Labels: bug, duplicate, wontfix
