### ISSUE TITLE
Adding to playlist when song already present

### ISSUE THREAD

**Issue by ajmeese7** [MahdiGhiasi/Xpotify#40] opened 2019-07-26 16:01 UTC
On the Spotify client, whenever you try to add a song to a playlist where it is already there, there is a pop-up confirming if you want to add the duplicate anyways or skip adding it. On Xpo, it adds the song anyways without letting you know if it is already there.

It would be nice to see this Spotify feature mimicked in Xpo.

**Comment by MahdiGhiasi** [comment] 2019-07-27 17:53
Duplicate of #22

**Closed as completed by MahdiGhiasi** 2019-07-27 17:53 UTC
Labels: duplicate, enhancement
